version: '3'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["npm", "run", "test"]